### PR TITLE
PVE006 issue

### PR DESCRIPTION
**Pull request by maikelordaz**

### CODE REVIEW

**Comment by maikelordaz** [comment]
Fixed PVE006 issue with `totalYieldGenerated` missed PVE006-2 on `termAPY` and fixed bug on `yieldDistributionRatio`

**Review by MohammedTaka — COMMENTED** [review]
_sharesToEth is best moved to the yield generation library

**Review by MohammedTaka — COMMENTED** [review]
The formula on return is wrong. It should be

`return totalWithdrawnYield + _sharesToEth(currentShares, totalDeposit, totalShares) - currentTotalDeposit`

Using totalDeposit instead of currentTotalDeposit can cause an underflow. This is what PVE006 actually is and what oeckshield found. The _sharesToEth was supposed to be an additional fix on top of this.

**Comment by maikelordaz** [comment]
Fixed it

**Comment by maikelordaz** [comment]
Moved function to library

**Pull request merged**
