### PR TITLE
revise: fix yieldDistributionRatio

### PR DESCRIPTION
**Pull request by maikelordaz**

### CODE REVIEW

**Review by MohammedTaka — APPROVED** [review]
@elallamTaka please also check if the logic is sound/correct

**Review by MohammedTaka — APPROVED** [review]
A little bit dirty to put the function name change in this PR but it's acceptable for now.

**Review by elallamTaka — APPROVED** [review]
The logic looks sound to me, once someone withdraws part of their share, other users ratio compared to the total must increase. But if we use this to display the yield generated in the UI, user will see 0 after all withdrawals.

**Comment by MohammedTaka** [comment]
> The logic looks sound to me, once someone withdraws part of their share, other users ratio compared to the total must increase. But if we use this to display the yield generated in the UI, user will see 0 after all withdrawals.

No this is not true because we also keep track of how much yield was withdrawn. Meaning that what hte user sees is what is left to withdraw + what the user already has withdrawn.

**Pull request merged**
